### ISSUE TITLE
Maximum call stack size exceeded when using copy option for url 

### ISSUE THREAD

**Issue by devmondo** [postcss/postcss-url#35]
hi, 
i am using this on windows with gulp-postcss and i am getting the following error when i use copy option for url

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
RangeError: Maximum call stack size exceeded
    at new Error (native)
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at sync (d:\Websites\WAP\WAPUI\node_modules\postcss-url\node_modules\mkdirp\index.js:71:13)
    at sync (d:\Websites\WAP\WAPUI\node_modules\postcss-url\node_modules\mkdirp\index.js:77:24)
    at sync (d:\Websites\WAP\WAPUI\node_modules\postcss-url\node_modules\mkdirp\index.js:78:17)
    at sync (d:\Websites\WAP\WAPUI\node_modules\postcss-url\node_modules\mkdirp\index.js:78:17)
    at sync (d:\Websites\WAP\WAPUI\node_modules\postcss-url\node_modules\mkdirp\index.js:78:17)
    at sync (d:\Websites\WAP\WAPUI\node_modules\postcss-url\node_modules\mkdirp\index.js:78:17)
    at sync (d:\Websites\WAP\WAPUI\node_modules\postcss-url\node_modules\mkdirp\index.js:78:17)
```

my gulp implementation 

```
gulp.task('css', function () {
    var processors = [
        url({
            url: "copy" ,// or "inline" or "copy",
            assetsPath:'packed'
        })
    ];
    return gulp.src('bundle.css')
        .pipe(postcss(processors,{to:'./temp/dist'}))
        .pipe(gulp.dest('./temp/dist'));
});
```

thanks in advanced.

**Comment by MoOx** [comment]
Hum that's weird. It seems you have a path that is causing a recursive issue.
Can you take some time to push some failings tests so we can fix this bug more quickly please ?

**Comment by akrawitz** [comment]
I've run in to the same issue. I don't think any new tests are needed, as many existing tests for `url: "copy"` will already fail if they are run on Windows. The problem, generally speaking, is that the `processCopy()` function in _index.js_ mixes URL paths and file paths as if they were interchangeable. This particular manifestation of the problem is in line 333 in _index.js_:
```javascript
dirname.replace(new RegExp(from + "[\/]\?"), ""),
```
The RegExp is created using the `from` file path, but if that path uses '\' as the separator, this won't work without proper escaping. A quick fix would be to change it to something like:
```javascript
dirname.replace(new RegExp(from.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "[\/]\?"), ""),
```
However, it would probably be better to come up with a cleaner way to find the common base path.

**Comment by MoOx** [comment]
You should better check postcss-copy

**Comment by devmondo** [comment]
thanks :)
